### ISSUE TITLE
`npm run clean:all` error: `Error: Cannot find module './hash/md4'`

### ISSUE THREAD

**Issue by benloh** [Vertex-Labs/meme#2]
As of dev-ds/package-updates-ds01 aae84af3ef49454278096f1b1c5ce236e66929dd, on an Intel Ventura 13.6.6 machine, running the following...

```
nvm install v18.20.2
nvm use
npm ci
npm run clean:all
```

...results in this error:
```
loh@clickr meme % npm run clean:all

> meme-boilerplate@1.3.0 clean:all
> node meme clean --all

PATH         -- codebase located at: /Users/loh/dev/meme/src
PATH         -- meme root folder located at: /Users/loh/dev/meme
viewsPath:  /Users/loh/dev/meme/built/web/
UR_EXPRESS   - COMPILING WEBSERVER w/ WEBPACK - THIS MAY TAKE SEVERAL SECONDS...
WEBPACK      - ... using webpack.base.config
WEBPACK      - ... using webpack.webapp.config

Dev server running.
Open browser to http://localhost:3000
MEME EXEC    - removing dist/, data/, and built/ directories...
MEME EXEC    - directories removed!
MEME EXEC    - also removing node_modules/
MEME EXEC    - you will have to reinstall them with the
MEME EXEC    - npm ci command.
MEME EXEC    - operation complete!
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module './hash/md4'
Require stack:
- /Users/loh/dev/meme/node_modules/webpack/lib/util/createHash.js
- /Users/loh/dev/meme/node_modules/webpack/lib/serialization/ObjectMiddleware.js
- /Users/loh/dev/meme/node_modules/webpack/lib/util/serialization.js
- /Users/loh/dev/meme/node_modules/webpack/lib/util/makeSerializable.js
- /Users/loh/dev/meme/node_modules/webpack/lib/WebpackError.js
- /Users/loh/dev/meme/node_modules/webpack/lib/DefinePlugin.js
- /Users/loh/dev/meme/node_modules/webpack/lib/index.js
- /Users/loh/dev/meme/src/config/webpack.webapp.config.js
- /Users/loh/dev/meme/src/system/server-express.js
- /Users/loh/dev/meme/src/system/server.js
- /Users/loh/dev/meme/meme.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at module.exports (/Users/loh/dev/meme/node_modules/webpack/lib/util/createHash.js:169:17)
    at /Users/loh/dev/meme/node_modules/webpack/lib/DefinePlugin.js:349:22
    at Hook.eval [as call] (eval at create (/Users/loh/dev/meme/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/loh/dev/meme/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/loh/dev/meme/node_modules/webpack/lib/Compiler.js:1139:26)
    at /Users/loh/dev/meme/node_modules/webpack/lib/Compiler.js:1183:29 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/loh/dev/meme/node_modules/webpack/lib/util/createHash.js',
    '/Users/loh/dev/meme/node_modules/webpack/lib/serialization/ObjectMiddleware.js',
    '/Users/loh/dev/meme/node_modules/webpack/lib/util/serialization.js',
    '/Users/loh/dev/meme/node_modules/webpack/lib/util/makeSerializable.js',
    '/Users/loh/dev/meme/node_modules/webpack/lib/WebpackError.js',
    '/Users/loh/dev/meme/node_modules/webpack/lib/DefinePlugin.js',
    '/Users/loh/dev/meme/node_modules/webpack/lib/index.js',
    '/Users/loh/dev/meme/src/config/webpack.webapp.config.js',
    '/Users/loh/dev/meme/src/system/server-express.js',
    '/Users/loh/dev/meme/src/system/server.js',
    '/Users/loh/dev/meme/meme.js'
  ]
}

```

**Comment by benloh** [comment]
Won't fix.  Wrong branch.  Should have been `dev-vertex/packages-updated`
